modeling:
  n_trials: 5
  model_family: catboost
  objective_function: Logloss # Logloss, CrossEntropy
  loss_function: Precision # Precision, F1, Accuracy

categorical_features:
- State
- Sex
- GeneralHealth
- LastCheckupTime
- PhysicalActivities
- RemovedTeeth
- HadAngina
- HadStroke
- HadAsthma
- HadSkinCancer
- HadCOPD
- HadDepressiveDisorder
- HadKidneyDisease
- HadArthritis
- HadDiabetes
- DeafOrHardOfHearing
- BlindOrVisionDifficulty
- DifficultyConcentrating
- DifficultyWalking
- DifficultyDressingBathing
- DifficultyErrands
- SmokerStatus
- ECigaretteUsage
- ChestScan
- RaceEthnicityCategory
- AgeCategory
- AlcoholDrinkers
- HIVTesting
- FluVaxLast12
- PneumoVaxEver
- TetanusLast10Tdap
- HighRiskLastYear
- CovidPos